// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table user {
  id integer [primary key]
  name varchar
  email varchar
  hash_pasword varchar
  created_at timestamp
}

Table list {
  id integer [primary key]
  name varchar
  position integer
  owner integer
  created_at timestamp
}

Table card {
  id integer [primary key]
  name varchar
  list integer
  description text
  position integer
  owner integer
  created_at timestamp
}

Table comment {
  id integer [primary key]
  description varchar
  owner integer
  card integer
  created_at timestamp
}

Ref: card.list > list.id

Ref: comment.owner > user.id

Ref: list.owner > user.id

Ref: card.owner > user.id

Ref: comment.card > card.id
